

name: Node.js CI/CD Pipeline

# Trigger the workflow on push or pull request events to the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 5: Build Docker image
      - name: Build Docker Image
        run: docker build -t node-docker-app .

      # Step 6: Optional: Log in to Docker Hub and push Docker image
      # Uncomment these steps if you want to push the Docker image to Docker Hub
      # Ensure you have added DOCKER_HUB_USERNAME and DOCKER_HUB_TOKEN secrets in your GitHub repository

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/node-docker-app